Write a NumPy program to implement following operation

1. To convert a list of numeric values into a 
one-dimensional NumPy array

In [1]:
# 216270307028
# Hasan Ravda

import numpy as np

# To convert a list of numeric values into a one-dimensional NumPy array
a=np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


2. To create a 3x3 matrix with values ranging 
from 2 to 10

In [2]:
a3=np.array([[2,3,4],[5,6,7],[8,9,10]])
print(a3)

matrix =np.arange(2,11,1).reshape(3,3)
print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3. To append values at the end of an array

In [3]:
newa=np.append(a,[6,7,8])
print(newa)

[1 2 3 4 5 6 7 8]


4. To create another shape from an array 
without changing its data (3x2 to 2x3) 

In [4]:
arr=np.array([[1,2],[3,4],[5,6]])
print("3x2 Array : \n",arr)

arr2=arr.reshape(2,3)
print("2x3 Array : \n",arr2)

3x2 Array : 
 [[1 2]
 [3 4]
 [5 6]]
2x3 Array : 
 [[1 2 3]
 [4 5 6]]
