## *Hasan Ravda     [ 216270307028 ]*

# Write a NumPy program to implement following operation


In [1]:
# Hasan Ravda
# 216270307028
import numpy as np

### 1. to find the maximum and minimum value of a given flattened array

In [2]:
arr=np.arange(1,10).reshape(3,3)
print("Original Array = \n",arr)

f_arr=arr.flatten()
print("Flattened Array =",f_arr)

max=np.max(f_arr)
print("\nMaximum of given flattened array = ",max)
min=np.min(f_arr)
print("Minimum of array = ",min)

Original Array = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattened Array = [1 2 3 4 5 6 7 8 9]

Maximum of given flattened array =  9
Minimum of array =  1


### 2. To compute the mean, standard deviation, and variance of a given array along the second axis

In [3]:
a=np.arange(1,7).reshape(2,3)
print(a)
print("Mean = ",np.mean(a,axis=1))
print("Standard deviation = ",np.std(a,axis=1))
print("Variance = ",np.var(a,axis=1))

[[1 2 3]
 [4 5 6]]
Mean =  [2. 5.]
Standard deviation =  [0.81649658 0.81649658]
Variance =  [0.66666667 0.66666667]
