# Hasan Ravda     [ 216270307028 ]

# Write a NumPy program to implement following operation


In [1]:
# Hasan Ravda
# 216270307028
import numpy as np

# 1. to find the maximum and minimum value of a given flattened array

In [2]:
arr=np.arange(1,10).reshape(3,3)
print("Original Array = \n",arr)

f_arr=arr.flatten()
print("Flattened Array =",f_arr)

max=np.max(f_arr)
print("\nMaximum of given flattened array = ",max)
min=np.min(f_arr)
print("Minimum of array = ",min)

Original Array = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattened Array = [1 2 3 4 5 6 7 8 9]

Maximum of given flattened array =  9
Minimum of array =  1


# 2. To compute the mean, standard deviation, and variance of a given array along the second axis

In [3]:
print(arr)
np.mean(arr)
np.std(arr)
np.var(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


6.666666666666667