Write a NumPy program to implement following operation


In [1]:
import numpy as np

1.  to add, subtract, multiply, divide arguments element-wise

In [2]:
a=np.arange(1,5)
print(a)
print("a+10 = ",a+10)
print("a-1 = ",a-1)
print("a*10 = ",a*10)
print("a/10 = ",a/10)
print("a**2 = ",a**2)
print("a%2 = ",a%2)

[1 2 3 4]
a+10 =  [11 12 13 14]
a-1 =  [0 1 2 3]
a*10 =  [10 20 30 40]
a/10 =  [0.1 0.2 0.3 0.4]
a**2 =  [ 1  4  9 16]
a%2 =  [1 0 1 0]


2. to round elements of the array to the nearest integer

In [3]:
f_arr=np.array([0.3,0.8,1.5,2.6,3.2,4.5])
np.round(f_arr)

array([0., 1., 2., 3., 3., 4.])

3. to calculate mean across dimension, in a 2D numpy array

In [4]:
a=np.arange(1,7).reshape(2,3)
print(a)

# mean across rows (axis=1)
r_mean=np.mean(a,axis=1)
print("mean across rows = ",r_mean)

# mean across columns (axis=0)
c_mean=np.mean(a,axis=0)
print("mean across columns = ",c_mean)

[[1 2 3]
 [4 5 6]]
mean across rows =  [2. 5.]
mean across columns =  [2.5 3.5 4.5]


4. to calculate the difference between neighboring elements, element wise of a given array

In [5]:
arr=np.array([1,3,6,9,13])
print("Original Array = ",arr)

diff=np.diff(arr)
print("Difference between elements = ",diff)

Original Array =  [ 1  3  6  9 13]
Difference between elements =  [2 3 3 4]
